### ISSUE TITLE
Failed to load the atom-yeoman package

### ISSUE THREAD

**Issue by weima-sage** [david-driscoll/atom-yeoman#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.2.0

### Stack Trace

Failed to load the atom-yeoman package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:10693:16
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:10966:21
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:8120:31
  at Function.template (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:10692:20)
  at Function.deprecate.object (/Users/wema/.atom/packages/atom-yeoman/node_modules/yeoman-generator/lib/util/deprecate.js:17:18)
  at Object.<anonymous> (/Users/wema/.atom/packages/atom-yeoman/node_modules/yeoman-generator/lib/base.js:188:36)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/wema/.atom/packages/atom-yeoman/node_modules/yeoman-generator/index.js:41:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/wema/.atom/packages/atom-yeoman/lib/generator.ts:9:9
  at Object.exports.allowUnsafeNewFunction (/Users/wema/.atom/packages/atom-yeoman/node_modules/loophole/lib/loophole.js:25:14)
  at /Users/wema/.atom/packages/atom-yeoman/lib/generator.ts:7:14
  at Object.<anonymous> (/Users/wema/.atom/packages/atom-yeoman/lib/generator.ts:57:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .ts] (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:99:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/wema/.atom/packages/atom-yeoman/lib/atom-yeoman.ts:4:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .ts] (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:99:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:691:34)
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:170:28
  at Package.module.exports.Package.measure (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.load (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:161:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:354:14)
  at /Users/wema/.atom/packages/omnisharp-atom/lib/omnisharp-atom/dependency-checker.ts:34:35
  at arrayEach (/Users/wema/.atom/packages/omnisharp-atom/node_modules/lodash/index.js:1361:13)
  at Function.<anonymous> (/Users/wema/.atom/packages/omnisharp-atom/node_modules/lodash/index.js:3405:13)
  at /Users/wema/.atom/packages/omnisharp-atom/lib/omnisharp-atom/dependency-checker.ts:32:15
  at counter (/Users/wema/.atom/packages/omnisharp-atom/node_modules/atom-package-dependencies/index.js:14:15)
  at /Users/wema/.atom/packages/omnisharp-atom/node_modules/atom-package-dependencies/index.js:67:7
  at /Users/wema/.atom/packages/omnisharp-atom/node_modules/atom-package-dependencies/node_modules/shelljs/src/exec.js:107:7
  at ChildProcess.exithandler (child_process.js:720:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  4x -3:10.2.0 core:backspace (atom-text-editor.editor.mini)
     -3:08.0 core:confirm (atom-text-editor.editor.mini)
  3x -2:39 core:backspace (atom-text-editor.editor.mini)
     -2:37.2.0 core:confirm (atom-text-editor.editor.mini)
     -1:51.6.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-atom-light-ui)
  5x -1:14.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
 15x -1:13.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode)
  3x -1:09.6.0 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autocomplete-plus, v2.12.1
language-fsharp, v0.8.4
linter, v0.12.1
omnisharp-atom, v0.4.12
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by jchannon** [comment]
I see the same

**Comment by Yantrio** [comment]
Me too :(

**Comment by unuunc** [comment]
me too

**Comment by sayedihashimi** [comment]
Same here

**Comment by nosami** [comment]
+1 ;)

**Comment by douglasstarnes** [comment]
Same here except on Linux

**Comment by bitbonk** [comment]
+1 (on Windows 7, which probably doesn't matter)

**Comment by ladislaolainez** [comment]
Same here. It was installing dependencies for Omnisharp, if that's of any help.

**Comment by oleyb** [comment]
Same issue on OSX 10.10.4 running Atom 0.200.0

I removed all packages, installed the omnisharp-atom package which then installs atom-yeoman as a dependency, and it fails with the message stated in this issue.

**Comment by jwjames83** [comment]
+1

**Comment by thiago-negri** [comment]
Same here. Installing dependencies for Omnisharp. +1

**Comment by oleyb** [comment]
Updating to the most recent release of Atom resolved the issue for me.

**Comment by david-driscoll** [comment]
Sounds like this should be resolved, let me know if it happens again!
