### ISSUE TITLE
Uncaught TypeError: Cannot read property 'makeRequest' of null

### ISSUE THREAD

**Issue by Camypaper** [david-driscoll/atom-yeoman#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Unknown Windows Version
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'makeRequest' of null

```
At C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'makeRequest' of null
  at Function.Omni.makeRequest (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:37:50)
  at GoToDefinition.goToDefinition (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:13:28)
  at AnonymousObserver._onNext (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:54:30)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:1894:35)
  at AnonymousObserver.tryCatcher (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:1894:35)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:5138:19)
  at Subject.tryCatcher (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:1894:35)
  at AutoDetachObserver.tryCatcher (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:1894:35)
  at HTMLDivElement.handler (C:\Users\camypaper\.atom\packages\atom-yeoman\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.async.js:457:20)

```

### Commands

```
     -0:05.8.0 application:new-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
file-icons, v1.5.5
japanese-wrap, v0.2.7
linter, v0.12.3
omnisharp-atom, v0.4.33

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
This is probably more omnisharp-atom related, and hopfully has been fixed in a recent version.  Give them a shot and reopen if its still a problem for you!
