### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by izaakschroeder** [david-driscoll/atom-yeoman#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At events.js:141

TypeError: Cannot read property 'split' of undefined
  at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:49:19)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:531:24)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:516:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:750:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:514:21)
  at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:451:19)
  at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:695:26)
  at TextEditorView.module.exports.TextEditorView.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/text-editor-view.js:52:25)
  at TextView.show (/Users/izaakschroeder/.atom/packages/atom-yeoman/lib/prompts/text-view.js:48:25)
  at AtomAdapter.runNextQuestion (/Users/izaakschroeder/.atom/packages/atom-yeoman/lib/atom-adapter.js:35:131)
  at AtomAdapter.prompt (/Users/izaakschroeder/.atom/packages/atom-yeoman/lib/atom-adapter.js:16:14)
  at [object Object].Base.prompt (/Users/izaakschroeder/Projects/metalab/stack/generator-gulp/node_modules/yeoman-generator/lib/base.js:227:20)
  at [object Object].module.exports.generators.Base.extend.prompting (/Users/izaakschroeder/Projects/metalab/stack/generator-gulp/task/index.js:12:8)
  at /Users/izaakschroeder/Projects/metalab/stack/generator-gulp/node_modules/yeoman-generator/lib/base.js:428:16
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
     -5:15.4.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -4:51.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -4:44.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:38.1.0 yo:yeoman (atom-text-editor.editor.mini.is-focused)
  4x -4:30.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:22.6.0 yo:yeoman (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-isotope-ui)
     -4:18.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:07.6.0 yo:yeoman (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-isotope-ui)
  9x -4:05.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.9.0 yo:yeoman (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-isotope-ui)
     -0:08.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view"
    ],
    "projectHome": "~/Projects"
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.5.0
atom-yeoman, v0.3.1
autocomplete-paths, v1.0.2
docblockr, v0.7.2
editorconfig, v1.0.0
file-icons, v1.5.5
isotope-ui, v2.4.0
language-asciidoc, v0.11.1
language-fish-shell, v1.0.2
language-gherkin, v1.0.2
language-haskell, v1.0.0
language-jade, v0.4.0
language-javascript-better, v1.5.0
linter, v0.12.6
linter-eslint, v0.5.8
linter-flow, v0.1.5
minimap, v4.9.0
sublime-tabs, v0.5.6
tabs-to-spaces, v0.11.0
travis-ci-status, v0.15.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
What generator were you running when this happened?
