### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/Martin/.atom/packages/atom-yeoman/lib/generator.js'

### ISSUE THREAD

**Issue by martinerk0** [david-driscoll/atom-yeoman#19]
[Enter steps to reproduce below:]

1. Got same:  https://github.com/OmniSharp/omnisharp-atom/issues/178
2. Downloaded updated:  https://github.com/david-driscoll/atom-yeoman/commit/b325f7ea0f14340a2391d0cdbd3f18fbc88d77ec
3. Manually installed using apm link & apm install

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Martin/.atom/packages/atom-yeoman/lib/generator.js'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/Martin/.atom/packages/atom-yeoman/lib/generator.js'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:138:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (/Users/Martin/.atom/packages/atom-yeoman/lib/generator-service.js:12:25)
  at atom-workspace.<anonymous> (/Users/Martin/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:71:116)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -9:50.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -9:43.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:36.5.0 omnisharp-atom:new-application (atom-text-editor.editor.mini.is-focused)
  3x -6:34.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.mini.is-focused)
     -6:29 application:new-file (atom-text-editor.editor.is-focused)
     -6:25.2.0 omnisharp-atom:new-application (atom-text-editor.editor.is-focused)
     -6:19.7.0 omnisharp-atom:toggle (atom-text-editor.editor.is-focused)
     -6:12.4.0 package-generator:generate-package (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:17.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:02.2.0 omnisharp-atom:new-application (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus",
      "autocomplete-snippets",
      "autocomplete-html",
      "autocomplete-css"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.3
color-picker, v2.0.2
haskell-ghc-mod, v0.6.3
ide-haskell, v0.5.7
language-glsl, v2.0.0
language-haskell, v1.0.0
linter, v0.12.6
omnisharp-atom, v0.9.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try out the latest version, I hope this is squashed once and for all.
