### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by austincummings** [david-driscoll/atom-yeoman#20]
**Steps:**
1. Install atom-yeoman
2. Restart atom
2. Open command pallete and run the "Yo: Yeoman" command

**Atom Version**: 0.204.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.1

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10754

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10747:16
  at C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:11020:21
  at C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:8094:31
  at Function.template (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10746:20)
  at Function.deprecate.object (C:\Users\austin\.atom\packages\atom-yeoman\node_modules\yeoman-generator\lib\util\deprecate.js:17:18)
  at Object.<anonymous> (C:\Users\austin\.atom\packages\atom-yeoman\node_modules\yeoman-generator\lib\base.js:188:36)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\austin\.atom\packages\atom-yeoman\node_modules\yeoman-generator\index.js:41:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at C:\Users\austin\.atom\packages\atom-yeoman\lib\generator.js:9:9
  at Object.exports.allowUnsafeNewFunction (C:\Users\austin\.atom\packages\atom-yeoman\node_modules\loophole\lib\loophole.js:25:14)
  at C:\Users\austin\.atom\packages\atom-yeoman\lib\generator.js:7:14
  at Object.<anonymous> (C:\Users\austin\.atom\packages\atom-yeoman\lib\generator.js:57:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.<anonymous> (C:\Users\austin\.atom\packages\atom-yeoman\lib\atom-yeoman.js:12:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\austin\AppData\Local\atom\app-0.204.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -0:17.5.0 command-palette:toggle (atom-pane.pane.active)
     -0:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.7.0 yo:yeoman (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Users\\Austin\\Workspace"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
autocomplete-python, v0.4.1
dart-tools, v0.9.12
editorconfig, v1.0.0
file-icons, v1.5.6
hex, v0.6.2
highlight-selected, v0.9.3
keybinding-cheatsheet, v0.0.9
language-ilasm, v0.0.1
linter, v0.12.6
minimap, v4.9.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try out the latest version, I hope this is squashed once and for all.
