### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by atopala** [david-driscoll/atom-yeoman#21]
[Enter steps to reproduce below:]

1. Menu action: Packages / OmniSharp / New Application

**Atom Version**: 0.205.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.1

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10754

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10747:16
  at C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:11020:21
  at C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:8094:31
  at Function.template (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10746:20)
  at Function.deprecate.object (C:\Users\xxx\.atom\packages\atom-yeoman\node_modules\yeoman-generator\lib\util\deprecate.js:17:18)
  at Object.<anonymous> (C:\Users\xxx\.atom\packages\atom-yeoman\node_modules\yeoman-generator\lib\base.js:188:36)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\xxx\.atom\packages\atom-yeoman\node_modules\yeoman-generator\index.js:41:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator.js:9:9
  at Object.exports.allowUnsafeNewFunction (C:\Users\xxx\.atom\packages\atom-yeoman\node_modules\loophole\lib\loophole.js:25:14)
  at C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator.js:7:14
  at Object.<anonymous> (C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator.js:57:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator-service.js:12:25)
  at atom-workspace.<anonymous> (C:\Users\xxx\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:54:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\xxx\AppData\Local\atom\app-0.205.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
  2x -0:45.7.0 omnisharp-atom:toggle (div.settings-view.pane-item)
     -0:26.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.6.0 omnisharp-atom:new-application (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
autocomplete-plus-async, v0.22.0
linter, v0.12.6
omnisharp-atom, v0.10.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try out the latest version, I hope this is squashed once and for all.
