### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by DarkKilauea** [david-driscoll/atom-yeoman#22]
[Enter steps to reproduce below:]

1. Invoked OmniSharp's (0.10.0) New Application command.
2. Error thrown.

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.1

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:10754

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:10747:16
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:11020:21
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:8094:31
  at Function.template (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:10746:20)
  at Function.deprecate.object (/Users/joshua/.atom/packages/atom-yeoman/node_modules/yeoman-generator/lib/util/deprecate.js:17:18)
  at Object.<anonymous> (/Users/joshua/.atom/packages/atom-yeoman/node_modules/yeoman-generator/lib/base.js:188:36)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/joshua/.atom/packages/atom-yeoman/node_modules/yeoman-generator/index.js:41:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/joshua/.atom/packages/atom-yeoman/lib/generator.js:9:9
  at Object.exports.allowUnsafeNewFunction (/Users/joshua/.atom/packages/atom-yeoman/node_modules/loophole/lib/loophole.js:25:14)
  at /Users/joshua/.atom/packages/atom-yeoman/lib/generator.js:7:14
  at Object.<anonymous> (/Users/joshua/.atom/packages/atom-yeoman/lib/generator.js:57:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (/Users/joshua/.atom/packages/atom-yeoman/lib/generator-service.js:12:25)
  at atom-workspace.<anonymous> (/Users/joshua/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:54:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:49.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -2:42.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:36.9.0 settings-view:check-for-package-updates (atom-text-editor.editor)
     -1:02.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:56.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.0 omnisharp-atom:new-application (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/joshua/Documents/Development/"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
linter, v0.12.6
omnisharp-atom, v0.10.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try out the latest version, I hope this is squashed once and for all.
