### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, readlink '/Users/wk/.atom/packages/atom-yeoman'

### ISSUE THREAD

**Issue by somnuk-wk** [david-driscoll/atom-yeoman#23]
[Enter steps to reproduce below:]

1. Package -> OmniSharp -> New Application
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: EINVAL: invalid argument, readlink '/Users/wk/.atom/packages/atom-yeoman'

```
At fs.js:864

Error: EINVAL: invalid argument, readlink '/Users/wk/.atom/packages/atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at /Users/wk/.atom/packages/atom-yeoman/lib/generator.js:25:30
  at arrayMap (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1431:25)
  at Function.map (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:6693:14)
  at /Users/wk/.atom/packages/atom-yeoman/lib/generator.js:22:7
  at Object.<anonymous> (/Users/wk/.atom/packages/atom-yeoman/lib/generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (/Users/wk/.atom/packages/atom-yeoman/lib/generator-service.js:13:25)
  at atom-workspace.<anonymous> (/Users/wk/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:67:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -2:08.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -2:08.4.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:07.5.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:07.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -2:02.2.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:01.7.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:00.9.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:00.1.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:59.5.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:59.3.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:58.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -1:56.2.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:54.8.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:27.8.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.6.0 omnisharp-atom:code-format (a.omnisharp-atom-button)
     -0:02.9.0 omnisharp-atom:new-application (a.omnisharp-atom-button)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-fsharp, v0.4.8
atom-runner, v2.4.1
atom-typescript, v4.5.7
atom-yeoman, v0.3.6
linter, v0.12.6
omnisharp-atom, v0.12.0
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Looks related to #30, let me know if its still an issue!
