### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, readlink '/Users/danielwalsh/.atom/packages/atom-yeoman'

### ISSUE THREAD

**Issue by dangwalsh** [david-driscoll/atom-yeoman#24]
[Enter steps to reproduce below:]

1. Click on Omnisharp > New Application 

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: EINVAL: invalid argument, readlink '/Users/danielwalsh/.atom/packages/atom-yeoman'

```
At fs.js:864

Error: EINVAL: invalid argument, readlink '/Users/danielwalsh/.atom/packages/atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at /Users/danielwalsh/.atom/packages/atom-yeoman/lib/generator.js:25:30
  at arrayMap (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1431:25)
  at Function.map (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:6693:14)
  at /Users/danielwalsh/.atom/packages/atom-yeoman/lib/generator.js:22:7
  at Object.<anonymous> (/Users/danielwalsh/.atom/packages/atom-yeoman/lib/generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (/Users/danielwalsh/.atom/packages/atom-yeoman/lib/generator-service.js:13:25)
  at atom-workspace.<anonymous> (/Users/danielwalsh/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:67:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:04.3.0 omnisharp-atom:new-application (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "irc",
      "navigate"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.6.4
atom-yeoman, v0.3.6
autocomplete-clang, v0.7.0
color-picker, v2.0.4
go-find-references, v1.2.3
language-jade, v0.4.0
linter, v0.12.7
linter-cpplint, v0.1.4
linter-csslint, v0.0.13
linter-golinter, v0.1.0
linter-jshint, v0.1.6
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
omnisharp-atom, v0.12.5
project-manager, v1.15.10
seti-syntax, v0.4.0
seti-ui, v0.7.1
tabs, v0.80.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Looks related to #30, let me know if its still an issue!
