### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [david-driscoll/atom-yeoman#25]
[Enter steps to reproduce below:]

1. Open Atom
2. Run `Yo: Yeoman` command

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\Krzysztof\.atom\packages\atom-yeoman'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\Krzysztof\.atom\packages\atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\Krzysztof\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\Krzysztof\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\Krzysztof\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.<anonymous> (C:\Users\Krzysztof\.atom\packages\atom-yeoman\lib\atom-yeoman.js:12:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Krzysztof\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -0:09.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.4.0 yo:yeoman (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-fsharp, v0.0.0
atom-yeoman, v0.3.6
file-icons, v1.5.7
flex-tool-bar, v0.4.2
indent-guide-improved, v1.2.1
Repl, v0.2.0
tool-bar, v0.1.7

# Dev
No dev packages
```

**Comment by theCrispy** [comment]
Steps to reproduce:

- see above

**Atom Version**: 0.209.0
**System**: Windows 10 - Build 10130
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6


### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\Christian\.atom\packages\omnisharp-atom'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\Christian\.atom\packages\omnisharp-atom'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\Christian\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\Christian\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\Christian\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.<anonymous> (C:\Users\Christian\.atom\packages\atom-yeoman\lib\atom-yeoman.js:12:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Christian\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -0:14.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 yo:yeoman (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ex-mode",
      "vim-mode"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.5.6
atom-yeoman, v0.3.6
linter, v0.12.7
omnisharp-atom, v0.14.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Looks related to #30, let me know if its still an issue!
