### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\xxx\.atom\packages\atom-yeoman'

### ISSUE THREAD

**Issue by atopala** [david-driscoll/atom-yeoman#26]
[Enter steps to reproduce below:]

1. Menu action: "Packages" / "atom-yoman" / "Toggle"

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\xxx\.atom\packages\atom-yeoman'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\xxx\.atom\packages\atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\xxx\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.<anonymous> (C:\Users\xxx\.atom\packages\atom-yeoman\lib\atom-yeoman.js:12:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\xxx\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
  5x -2:10.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -2:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:05.2.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:03.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:00.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:58.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:57.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:57.1.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -1:56.5.0 autoflow:reflow-selection (atom-text-editor.editor.is-focused)
  2x -1:53.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -1:53.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:51.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:51.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:50.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:32 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 yo:yeoman (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.6
keyboard-localization, v1.4.3
linter, v0.12.7
omnisharp-atom, vundefined

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Looks related to #30, let me know if its still an issue!
