### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\Yves\.atom\packages\atom-yeoman'

### ISSUE THREAD

**Issue by yreynhout** [david-driscoll/atom-yeoman#27]
[Enter steps to reproduce below:]

1. Install Omnisharp Atom
2. Open a folder
3. CTRL+SHIFT+P: Omnisharp New Application
4. Boom

**Atom Version**: 0.210.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\Yves\.atom\packages\atom-yeoman'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\Yves\.atom\packages\atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\Yves\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\Yves\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\Yves\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (C:\Users\Yves\.atom\packages\atom-yeoman\lib\generator-service.js:13:25)
  at atom-workspace.<anonymous> (C:\Users\Yves\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:89:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Yves\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:16.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:06.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 omnisharp-atom:new-application (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-fsharp, vundefined
atom-yeoman, v0.3.6
linter, v0.12.7
omnisharp-atom, v0.15.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Looks related to #30, let me know if its still an issue!
