### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, readlink '/Users/pvandorp/.atom/packages/atom-yeoman'

### ISSUE THREAD

**Issue by pvandorp** [david-driscoll/atom-yeoman#28]
[Enter steps to reproduce below:]

1. Install Atom on Mac Yosemite
2. Install atom-omnisharp package
3. Select new application in the OmniSharp package

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: EINVAL: invalid argument, readlink '/Users/pvandorp/.atom/packages/atom-yeoman'

```
At fs.js:864

Error: EINVAL: invalid argument, readlink '/Users/pvandorp/.atom/packages/atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at /Users/pvandorp/.atom/packages/atom-yeoman/lib/generator.js:25:30
  at arrayMap (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1431:25)
  at Function.map (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:6693:14)
  at /Users/pvandorp/.atom/packages/atom-yeoman/lib/generator.js:22:7
  at Object.<anonymous> (/Users/pvandorp/.atom/packages/atom-yeoman/lib/generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (/Users/pvandorp/.atom/packages/atom-yeoman/lib/generator-service.js:13:25)
  at atom-workspace.<anonymous> (/Users/pvandorp/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:89:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Users/pvandorp/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
  2x -2:31.4.0 omnisharp-atom:new-application (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.6
linter, v0.12.7
omnisharp-atom, v0.15.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Looks related to #30, let me know if its still an issue!
