### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\christian.duhard\.atom\packages\atom-y...

### ISSUE THREAD

**Issue by cduhard** [david-driscoll/atom-yeoman#29]
[Enter steps to reproduce below:]

1. CTRL-SHIFT-P
2. omni new app <enter>
3. boom

**Atom Version**: 0.210.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\christian.duhard\.atom\packages\atom-yeoman'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\christian.duhard\.atom\packages\atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\christian.duhard\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\christian.duhard\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\christian.duhard\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (C:\Users\christian.duhard\.atom\packages\atom-yeoman\lib\generator-service.js:13:25)
  at atom-workspace.<anonymous> (C:\Users\christian.duhard\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:89:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\christian.duhard\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -1:28.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -1:22.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:20.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:20.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:20.2.0 omnisharp-atom:new-application (atom-text-editor.editor.vim-mode.command-mode)
     -0:46.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:45.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:45.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:45.5.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:44.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:38.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -0:36.5.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -0:12.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -0:08.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 omnisharp-atom:new-application (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.6
linter, v0.12.7
minimap, v4.10.0
omnisharp-atom, v0.15.0
seti-ui, v0.7.1
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
see #30
