### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\jason\.atom\packages\omnisharp-atom'

### ISSUE THREAD

**Issue by nosami** [david-driscoll/atom-yeoman#30]
[Enter steps to reproduce below:]

1. ... Brand new Windows install... installed Atom and omnisharp-atom only
2. ... OmniSharp: New Application

**Atom Version**: 0.210.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\jason\.atom\packages\omnisharp-atom'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\jason\.atom\packages\omnisharp-atom'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\jason\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\jason\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\jason\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (C:\Users\jason\.atom\packages\atom-yeoman\lib\generator-service.js:13:25)
  at atom-workspace.<anonymous> (C:\Users\jason\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:89:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\jason\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.6
linter, v0.12.7
omnisharp-atom, v0.15.1

# Dev
No dev packages
```

**Comment by Dechowmedia** [comment]
Having the exact same issue.
This even happens just at creating a simple class.

[Enter steps to reproduce below:]

1. Open project bar ( ctrl+shift+p )
2. Omnisharp New Class
3. Select the option Omnisharp Atom: New Class
4. Stack trace and Error as shown below

**Atom Version**: 0.210.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.6


### Stack Trace

Uncaught Error: UNKNOWN: unknown error, readlink 'C:\Users\lde\.atom\packages\atom-yeoman'

```
At fs.js:864

Error: UNKNOWN: unknown error, readlink 'C:\Users\lde\.atom\packages\atom-yeoman'
  at Error (native)
  at Object.fs.readlinkSync (fs.js:864:18)
  at C:\Users\lde\.atom\packages\atom-yeoman\lib\generator.js:25:30
  at arrayMap (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1431:25)
  at Function.map (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6693:14)
  at C:\Users\lde\.atom\packages\atom-yeoman\lib\generator.js:22:7
  at Object.<anonymous> (C:\Users\lde\.atom\packages\atom-yeoman\lib\generator.js:80:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (C:\Users\lde\.atom\packages\atom-yeoman\lib\generator-service.js:13:25)
  at atom-workspace.<anonymous> (C:\Users\lde\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:89:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -6:27.5.0 advanced-new-file:toggle (atom-text-editor.editor.is-focused)
 23x -6:20.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -5:51.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -5:43.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:41.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:41.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:38.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:29.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -5:24.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:21.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:21.8.0 omnisharp-atom:new-application (atom-text-editor.editor)
     -0:51.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -0:49.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:43.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:43.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43.1.0 omnisharp-atom:new-application (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "accents-ui",
      "bittersweet-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v0.2.0
advanced-new-file, v0.4.3
atom-ternjs, v0.6.4
atom-yeoman, v0.3.6
bittersweet-syntax, v0.1.1
block-travel, v1.0.2
color-picker, v2.0.5
docblockr, v0.7.2
emmet, v2.3.10
linter, v0.12.7
linter-jshint, v0.1.6
linter-less, v0.5.0
minimap, v4.10.0
omnisharp-atom, v0.15.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I'll take a look at this today.

**Comment by david-driscoll** [comment]
pushed v0.3.8 can you give it a shot and let me know if it solves the issue (and things are working).

**Comment by Dechowmedia** [comment]
It gave me a new error upon creating a project

[Enter steps to reproduce below:]

1. Ctrl+Shift+P
2. Select the option Omnisharp Atom: New Application

Same applies for Class

Stack trace and Error as shown below


**Atom Version**: 0.210.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.8


### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


```
At C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10754

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10747:16
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:11020:21
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:8094:31
  at Function.template (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:10746:20)
  at Function.deprecate.object (C:\Users\lde\.atom\packages\atom-yeoman\node_modules\yeoman-generator\lib\util\deprecate.js:17:18)
  at Object.<anonymous> (C:\Users\lde\.atom\packages\atom-yeoman\node_modules\yeoman-generator\lib\base.js:195:36)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\lde\.atom\packages\atom-yeoman\node_modules\yeoman-generator\index.js:41:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at C:\Users\lde\.atom\packages\atom-yeoman\lib\generator.js:46:9
  at Object.exports.allowUnsafeNewFunction (C:\Users\lde\.atom\packages\atom-ternjs\node_modules\loophole\lib\loophole.js:25:14)
  at C:\Users\lde\.atom\packages\atom-yeoman\lib\generator.js:44:14
  at Object.<anonymous> (C:\Users\lde\.atom\packages\atom-yeoman\lib\generator.js:85:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at GeneratorService.run (C:\Users\lde\.atom\packages\atom-yeoman\lib\generator-service.js:13:25)
  at atom-workspace.<anonymous> (C:\Users\lde\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:89:140)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\lde\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:25.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:18.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.1.0 omnisharp-atom:new-application (atom-text-editor.editor)
     -0:15.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "accents-ui",
      "bittersweet-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v0.2.0
atom-ternjs, v0.6.4
atom-yeoman, v0.3.8
bittersweet-syntax, v0.1.1
block-travel, v1.0.2
color-picker, v2.0.6
docblockr, v0.7.2
emmet, v2.3.10
linter, v0.12.7
linter-jshint, v0.1.6
linter-less, v0.5.0
minimap, v4.10.0
omnisharp-atom, v0.15.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Yeah I saw that too, and then it went away... sigh.  Looking at it!

**Comment by david-driscoll** [comment]
v0.3.9? :+1:

**Comment by Dechowmedia** [comment]
This works :) - At least the problem is fixed for me with this update :)
