### ISSUE TITLE
Failed to activate the atom-yeoman package

### ISSUE THREAD

**Issue by cetchells** [david-driscoll/atom-yeoman#31]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.11

### Stack Trace

Failed to activate the atom-yeoman package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\chris\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\chris\.atom\packages\atom-yeoman\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\behavior.js:7:13)
    at Object.<anonymous> (C:\Users\chris\.atom\packages\atom-yeoman\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\behavior.js:120:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\chris\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
color-picker, v2.0.7
grunt-runner, v0.10.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Has this happened again?  I don't have a direct dependency on underscore-plus, but it could be related somehow.

**Comment by datanotion** [comment]
This just happened to me.  It showed up right after restarting Atom, after a failed attempt to install https://atom.io/packages/omnisharp-atom

Failed to activate the atom-yeoman package
Error parsing /Users/pat/.atom/packages/atom-yeoman/node_modules/event-kit/node_modules/grim/node_modules/emissary/package.json: Unexpected end of input

It ate my CPU for 10 minutes so I had to kill Atom, then restarted it.

So in my case, I'll bet it just wasn't fully written out.

Uninstalling and reinstalling atom-yeoman resolved the error for me.

Just an FYI in case others come here.

**Comment by wmeints** [comment]
Had the same issue. I used the following steps to resolve the problem:

1. Open a terminal window and execute the command `apm uninstall atom-yeoman`
2. Run the command `apm install atom-yeoman`

After that the message disappears and everything works as expected.

**Comment by andycmaj** [comment]
looks like it's now happening for `loophole` dependency.

[Enter steps to reproduce below:]

1. start atom.

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.15


### Stack Trace

Failed to activate the atom-yeoman package

```
At Cannot find module 'loophole'

Error: Cannot find module 'loophole'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/acunningham/.homesick/repos/packages/home/.atom/packages/atom-yeoman/lib/lodash.js:1:95)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/acunningham/.homesick/repos/packages/home/.atom/packages/atom-yeoman/lib/atom-yeoman.js:1:88)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Bootstrapper.activate (/Users/acunningham/.homesick/repos/packages/home/.atom/packages/atom-yeoman/lib/bootstrapper.js:9:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:191:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:831:28
```

### Commands

```
     -0:01.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -0:00.5.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax-dark.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "vim-surround",
      "json-schema",
      "language-aspx",
      "language-cshtml",
      "smalls",
      "exception-reporting",
      "metrics",
      "autocomplete-snippets",
      "timecop",
      "styleguide",
      "source-preview-babel",
      "markdown-preview",
      "python-tools"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules",
      "bin",
      "obj",
      ".artifacts",
      ".tools",
      ".vs"
    ],
    "packagesWithKeymapsDisabled": [
      "notifications"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ],
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (inactive)
advanced-open-file, v0.16.5 (inactive)
ariake-dark-syntax, v0.1.3 (inactive)
atom-material-syntax, v1.0.2 (inactive)
atom-material-syntax-dark, v0.2.7 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-monokai, v0.10.7 (inactive)
atom-yeoman, v0.3.15 (inactive)
base16-papercolor-dark-syntax, v0.2.0 (inactive)
base16-papercolor-light-syntax, v0.2.0 (inactive)
character-table, v0.4.3 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
clipboard-plus, v0.5.1 (inactive)
emerald-dream-syntax, v0.2.3 (inactive)
es-identifier-highlight, v0.4.3 (inactive)
esformatter, v2.2.0 (inactive)
ficus-syntax, v2.0.0 (inactive)
file-icons, v2.0.14 (inactive)
git-blame, v0.4.11 (inactive)
git-time-machine, v1.5.4 (inactive)
improved-chester-atom-syntax, v0.2.0 (inactive)
json-schema, v0.1.15 (inactive)
language-aspx, v0.5.0 (inactive)
language-babel, v2.53.0 (inactive)
language-cshtml, v0.2.1 (inactive)
language-docker, v1.1.7 (inactive)
language-terraform, v0.7.5 (inactive)
lazy-motion, v0.5.2 (inactive)
linter, v1.11.21 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-docker, v0.1.4 (inactive)
linter-eslint, v8.1.0 (inactive)
linter-python-pep8, v0.2.0 (inactive)
linter-terraform-syntax, v1.1.1 (inactive)
markdown-preview-enhanced, v0.9.5 (inactive)
material, v2.2.0 (inactive)
material-design-syntax, v1.8.0 (inactive)
material-monokai-syntax, v0.1.3 (inactive)
material-syntax, v0.6.1 (inactive)
monokai-seti, v0.7.0 (inactive)
monokai-shade, v0.3.5 (inactive)
monokai-slate, v0.6.0 (inactive)
nord-atom-syntax, v0.6.0 (inactive)
nord-atom-ui, v0.10.1 (inactive)
omnisharp-atom, v0.30.7 (inactive)
one-dark-material-syntax, v1.0.3 (inactive)
package-sync, v1.1.0 (inactive)
pane-move-plus, v0.3.1 (inactive)
prettier-atom, v0.15.0 (inactive)
prettier-eslint-atom, v2.0.1 (inactive)
pretty-json, v1.6.1 (inactive)
project-manager, v3.3.3 (inactive)
python-tools, v0.6.9 (inactive)
ramda-syntax, v0.12.0 (inactive)
relative-numbers, v0.7.1 (inactive)
rizzo-one, v0.5.0 (inactive)
robin-hood-syntax, v1.0.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.6.0 (inactive)
smalls, v0.2.0 (inactive)
snow-dark-material-syntax, v0.1.1 (inactive)
source-preview, v0.5.0 (inactive)
supine-syntax, v1.4.0 (inactive)
swackets, v0.26.0 (inactive)
swap-selection, v0.4.0 (inactive)
terraform-fmt, v0.3.0 (inactive)
trailing-semicolon, v1.1.0 (inactive)
vim-mode-clipboard-plus, v0.2.0 (inactive)
vim-mode-plus, v0.82.0 (inactive)
vim-surround, v0.8.1 (inactive)
warm-syntax, v1.0.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```
