### ISSUE TITLE
Uncaught TypeError: Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by OctoD** [david-driscoll/atom-yeoman#32]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.10
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.11
### Stack Trace

Uncaught TypeError: Cannot read property 'model' of undefined

```
At /home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'model' of undefined
  at /home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:203:68
  at ReplaySubject.Rx.ReplaySubject.addProperties.onNext (/home/octod/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:410:20)
  at AnonymousObserver._onNext (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:59:68)
  at AnonymousObserver._onCompleted (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:317:25)
  at AnonymousObserver._onCompleted (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:371:30)
  at AnonymousObserver._onNext (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:140:59)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver._onNext (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5079:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
  at Notification._acceptObservable (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1574:62)
  at Notification.Rx.Notification.Notification.accept (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1542:14)
  at /home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.time.js:203:26
  at scheduleInnerRecursive (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1085:7)
  at recursiveAction (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1063:9)
  at invokeRecDate (/home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1080:7)
  at /home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1126:16
  at /home/octod/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1432:60
From previous event:
    at new ReplaySubject (/home/octod/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:377:17)
    at new SolutionManager (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:22:32)
    at Object.<anonymous> (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:387:16)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Object.<anonymous> (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:2:15)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
From previous event:
    at new SolutionManager (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:23:62)
    at Object.<anonymous> (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:387:16)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Object.<anonymous> (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:2:15)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
From previous event:
  at Omni.Object.defineProperty.get [as activeModel] (/home/octod/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:203:41)
  at WorldModel.setupState (/home/octod/.atom/packages/omnisharp-atom/lib/omnisharp-atom/world.js:34:13)
  at WorldModel.activate (/home/octod/.atom/packages/omnisharp-atom/lib/omnisharp-atom/world.js:24:14)
  at /home/octod/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:96:31
```
### Commands

```
  2x -0:28.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:27.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.9.0 application:open-folder (atom-text-editor.editor)
     -0:17.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 yo:yeoman (atom-text-editor.editor)
     -0:11.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -0:09.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -0:08.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:07.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [],
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
atom-jade, v0.3.0
atom-yeoman, v0.3.11
color-picker, v2.0.7
emmet, v2.3.10
grunt-runner, v0.10.0
linter, v1.0.6
minimap, v4.10.0
omnisharp-atom, v0.16.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
What were the steps leading up to this error?

**Comment by OctoD** [comment]
Just simply choosed the generator with ctrl + shift + p -> yo. It works pretty normally without errors output when using command line and yeoman cli.
