### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by ccbentlee** [david-driscoll/atom-yeoman#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.11

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/Lee/.atom/packages/atom-yeoman/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'getGrammar' of undefined
    at FilterObservable.predicate (/Users/Lee/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:190:61)
    at /Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5130:46
    at tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5147:49)
    at InnerObserver.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
    at InnerObserver.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at Subject.Rx.Subject.addProperties.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
    at Subject.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
```

### Commands

```
     -1:57.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:57.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:55.3.0 yo:yeoman (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-material-ui)
     -1:54 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -1:49.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:41.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:18 script:run (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.7.0 yo:yeoman (atom-pane.pane.active)
  2x -0:20 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:19.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:17.6.0 yo:yeoman (atom-pane.pane.active)
     -0:16.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/Users/Lee/Documents",
    "ignoredNames": [
      "*.git",
      "*.meta",
      ".DS_Store",
      "obj",
      "Temp",
      "Library",
      "ProjectSettings",
      "*.csproj",
      "*.unityproj",
      "*.sln",
      "*.userprefs",
      ".gitignore",
      "*.class"
    ],
    "disabledPackages": [
      "javascript-snippets",
      "minimap-highlight-selected",
      "minimap-find-and-replace",
      "git-log",
      "docblockr",
      "pretty-json",
      "vim-mode",
      "git-plus",
      "merge-conflicts"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.4.3
atom-beautify, v0.28.8
atom-material-ui, v0.5.9
atom-yeoman, v0.3.11
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
file-icons, v1.6.2
highlight-selected, v0.10.1
jshint, v1.3.10
json-schema, v0.1.11
linter, v1.2.4
minimap, v4.12.1
omnisharp-atom, v0.23.1
pigments, v0.9.2

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Something coming from omnisharp, what were the steps that you had gone through to get here?
