### ISSUE TITLE
Uncaught TypeError: text.split is not a function

### ISSUE THREAD

**Issue by g3r4n** [david-driscoll/atom-yeoman#37]
[Enter steps to reproduce below:]
1. ctrl-Maj a -> yeoman
2. select esri-appbuilder-js theme
3. error catch after enter widget name

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.13
### Stack Trace

Uncaught TypeError: text.split is not a function

```
At C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:770

TypeError: text.split is not a function
  at Function.module.exports.Range.fromText (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\range.js:49:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:549:24)
  at C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:534:26
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:765:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:532:21)
  at TextBuffer.module.exports.TextBuffer.setText (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:472:19)
  at TextEditor.module.exports.TextEditor.setText (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:720:26)
  at TextEditorView.module.exports.TextEditorView.setText (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\text-editor-view.js:56:25)
  at TextView.show (C:\Users\edesvaux\.atom\packages\atom-yeoman\lib\prompts\text-view.js:47:25)
  at AtomAdapter.runNextQuestion (C:\Users\edesvaux\.atom\packages\atom-yeoman\lib\atom-adapter.js:35:131)
  at AtomAdapter.saveAnswer (C:\Users\edesvaux\.atom\packages\atom-yeoman\lib\atom-adapter.js:43:14)
  at TextView.invokeNext (C:\Users\edesvaux\.atom\packages\atom-yeoman\lib\atom-adapter.js:35:86)
  at TextView.confirmed (C:\Users\edesvaux\.atom\packages\atom-yeoman\lib\prompts\text-view.js:65:18)
  at HTMLBodyElement.<anonymous> (C:\Users\edesvaux\.atom\packages\atom-yeoman\lib\prompts\text-view.js:40:105)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\edesvaux\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```
### Commands

```
     -0:22.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:20.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.1.0 yo:yeoman (atom-text-editor.editor)
  4x -0:16.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -0:12.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.13
bottom-dock, v0.3.5
gulp-manager, v0.2.8

# Dev
No dev packages
```

**Comment by g3r4n** [comment]
Closing due to inactivity. I'm not using atom or yeoman anymore.
