### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by saipuli** [david-driscoll/atom-yeoman#41]
1. Open atom using the Cmd + Space and type atom or form Launchpad
2. Cmd + Shift + P for command window and type "Omnisharp Atom: New Project" OR Packages menu > OmniSharp > New Project. 
3. When finder windows pops up, press Esc or cancel button to exit out of finder and this error happened.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.3.15
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:210

TypeError: Cannot read property 'length' of null
    at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:210:41)
    at /Users/spuli/.atom/packages/atom-yeoman/lib/generator.js:127:38
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:400:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -2:07.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -2:04.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:04.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:04.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:58.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:18.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 omnisharp-atom:new-project (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v7.7.2
atom-yeoman, v0.3.15
json-schema, v0.1.15
language-csharp, v0.11.0
language-cshtml, v0.1.1
linter, v1.10.0
omnisharp-atom, v0.25.10

# Dev
No dev packages
```

**Comment by bandrzejczak** [comment]
:+1:
