### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by stvblank** [david-driscoll/atom-yeoman#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package 0.3.15

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At events.js:160

TypeError: Cannot read property 'then' of undefined
    at child.Base.prompt (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/index.js:168:44)
    at child.fountainPrompting (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/fountain-generator/lib/Base.js:109:17)
    at child.prompting (/usr/local/lib/node_modules/generator-fountain-webapp/generators/app/index.js:15:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/index.js:417:23)
    at /packages/atom-yeoman/node_modules/run-async/index.js:25:25
    at /packages/atom-yeoman/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -2:25.4.0 core:backspace (input.hidden-input)
     -2:25 core:confirm (input.hidden-input)
     -0:18.1.0 yo:yeoman (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-clock 0.1.11 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-yeoman 0.3.15 
aurora-theme 1.2.2 
browser-plus 0.0.97 
emmet 2.4.3 
flex-tool-bar 0.12.0 
ionic-preview 0.7.0 
language-sql-mysql 0.3.1 
minimap 4.28.2 
qolor 0.4.2 
terminal-plus 0.14.5 
tool-bar 1.1.0 
```

**Comment by jhessin** [comment]
[Enter steps to reproduce:]

1. Try to run anything with this package and ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package 0.3.15


### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At events.js:160

TypeError: Cannot read property 'then' of undefined
    at module.exports.prompt (/Users/jameshessin/Local Documents/websites/com.grillbrickstudios/node_modules/yeoman-generator/lib/index.js:155:46)
    at module.exports.prompting (/Users/jameshessin/Local Documents/websites/com.grillbrickstudios/node_modules/generator-coffee-react/generators/comp/index.js:27:17)
    at Object.<anonymous> (/Users/jameshessin/Local Documents/websites/com.grillbrickstudios/node_modules/yeoman-generator/lib/index.js:399:25)
    at /packages/atom-yeoman/node_modules/run-async/index.js:25:25
    at /packages/atom-yeoman/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/jameshessin/Local Documents/websites/com.grillbrickstudios/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -1:59.9.0 datatip:toggle (input.hidden-input)
     -1:53.3.0 editor:consolidate-selections (input.hidden-input)
     -1:53.3.0 core:cancel (input.hidden-input)
     -1:04.0 intentions:highlight (input.hidden-input)
  2x -1:03.9.0 datatip:toggle (input.hidden-input)
     -0:59.7.0 yo:yeoman (input.hidden-input)
     -0:59 datatip:toggle (input.hidden-input)
     -0:57.4.0 yo:yeoman (input.hidden-input)
     -0:57 datatip:toggle (input.hidden-input)
     -0:56.8.0 editor:consolidate-selections (input.hidden-input)
     -0:56.8.0 core:cancel (input.hidden-input)
     -0:35.9.0 yo:yeoman (input.hidden-input)
     -0:35.4.0 datatip:toggle (input.hidden-input)
  2x -0:34.5.0 core:move-down (input.hidden-input)
     -0:34 core:move-up (input.hidden-input)
     -0:28.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.8.1 
atom-yeoman 0.3.15 
auto-softwrap 1.0.1 
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
autocomplete-lua 0.9.0 
autocomplete-modules 1.10.0 
black-ui 0.3.5 
build-tools 4.5.12 
busy-signal 1.4.3 
chary-tree-view 0.2.13 
city-lights-icons 1.1.1 
coffee-navigator 0.0.18 
coffee-paste 0.8.0 
editorconfig 2.2.2 
hyperclick 0.0.0 
hyperclick-love 0.6.0 
hyperlink-hyperclick 1.3.4 
ide-flowtype 0.18.0 
indentation-indicator 1.1.0 
intentions 1.1.5 
ir-black-k-syntax 0.2.3 
js-hyperclick 1.13.0 
language-gitignore 0.3.0 
language-glsl 2.0.4 
language-lua 0.9.11 
language-markdown 0.25.1 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-eslint 8.4.1 
linter-flow-plus 3.1.0 
linter-luacheck 2.0.1 
linter-ui-default 1.6.10 
love-ide 0.17.0 
package-switch 0.5.0 
path-hyperclick 0.3.0 
platformio-ide-terminal 2.8.0 
prettier-atom 0.50.0 
space-tab 0.4.2 
standardjs-snippets 2.6.2 
sync-settings 0.8.3 
zentabs 0.8.9 
```

**Comment by idleberg** [comment]
Same here. I've already tried launching Atom with various harmony flags (e.g. `atom --js-flags="--harmony-shipping"`), but the problem persists.
