### ISSUE TITLE
Uncaught TypeError: this.callback is not a function

### ISSUE THREAD

**Issue by santiagoramirez** [david-driscoll/atom-yeoman#45]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.4
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package 0.3.15

### Stack Trace

Uncaught TypeError: this.callback is not a function

```
At /Users/Santiago/.atom/packages/atom-yeoman/lib/atom-adapter.js:23

TypeError: this.callback is not a function
    at AtomAdapter.runNextQuestion (/packages/atom-yeoman/lib/atom-adapter.js:23:25)
    at AtomAdapter.saveAnswer (/packages/atom-yeoman/lib/atom-adapter.js:45:14)
    at ConfirmView.invokeNext (/packages/atom-yeoman/lib/atom-adapter.js:34:89)
    at ConfirmView.TextView.confirmed (/packages/atom-yeoman/lib/prompts/text-view.js:66:18)
    at /packages/atom-yeoman/lib/prompts/text-view.js:82:105)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -7:44.1.0 command-palette:toggle (input.hidden-input)
  6x -7:41.4.0 core:backspace (input.hidden-input)
     -7:35.4.0 project-manager:list-projects (input.hidden-input)
  2x -7:17.8.0 editor:newline (input.hidden-input)
 12x -7:10.7.0 core:backspace (input.hidden-input)
     -3:24.3.0 command-palette:toggle (input.hidden-input)
  3x -3:17.4.0 core:backspace (input.hidden-input)
     -2:31.3.0 command-palette:toggle (input.hidden-input)
     -0:55.9.0 yo:yeoman (div.panels-item)
     -0:41.3.0 core:move-down (input.hidden-input)
  3x -0:40.9.0 core:confirm (input.hidden-input)
     -0:19.5.0 core:move-down (input.hidden-input)
     -0:19 core:move-up (input.hidden-input)
     -0:18.5.0 core:move-down (input.hidden-input)
  2x -0:17.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
activate-power-mode 1.2.0 
atom-beautify 0.29.17 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atom-monokai 0.10.9 
atom-terminal 0.8.0 
atom-underscore 0.1.3 
atom-yeoman 0.3.15 
atomic-chrome 0.3.0 
ax-monokai-syntax 0.1.0 
block-comment 0.4.3 
cake-syntax 1.0.2 
column-select 0.2.0 
cson 2.0.1 
firewatch-syntax 1.1.1 
git-plus 7.3.0 
git-time-machine 1.5.6 
github-atom-light-syntax 0.3.2 
greti-syntax 0.6.0 
gruvbox-plus-syntax 1.3.1 
gulp-control 0.5.0 
gulp-watcher 0.2.1 
language-apache 1.7.0 
language-ejs 0.4.0 
language-smarty 1.8.0 
minify-j-s 2.0.0 
modular-snippets 0.2.1 
monokai 0.24.0 
monokai-dark 1.3.0 
monokai-flat 1.0.1 
monokai-seti 0.9.0 
one-dark-vivid-syntax 1.7.1 
php-cs-fixer 4.1.0 
platformio-ide-terminal 2.2.3 
project-manager 3.3.3 
related 0.3.5 
remote-sync 4.1.5 
seti-syntax 1.1.2 
seti-ui 1.6.1 
snow-dark-syntax 0.1.1 
sublime-block-comment 0.5.1 
uglify 1.3.1 
```

**Comment by jhessin** [comment]
Just trying to run a simple generator and I get this issue.
