### ISSUE TITLE
Uncaught Error: input not supported yet.

### ISSUE THREAD

**Issue by luisrudge** [david-driscoll/atom-yeoman#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-yeoman](https://github.com/david-driscoll/atom-yeoman) package, v0.1.4

### Stack Trace

Uncaught Error: input not supported yet.

```
At events.js:141

Error: input not supported yet.
  at AtomAdapter.runNextQuestion (C:\Users\Luis\.atom\packages\atom-yeoman\lib\atom-adapter.ts:30:19)
  at AtomAdapter.prompt (C:\Users\Luis\.atom\packages\atom-yeoman\lib\atom-adapter.ts:15:14)
  at [object Object].Base.prompt (C:\Users\Luis\AppData\Roaming\npm\node_modules\generator-simple-aspnet\node_modules\yeoman-generator\lib\base.js:215:20)
  at [object Object].module.exports.yeoman.generators.Base.extend.prompting (C:\Users\Luis\AppData\Roaming\npm\node_modules\generator-simple-aspnet\app\index.js:23:10)
  at C:\Users\Luis\AppData\Roaming\npm\node_modules\generator-simple-aspnet\node_modules\yeoman-generator\lib\base.js:409:16
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
     -0:09.3.0 command-palette:toggle (atom-pane.pane.active)
     -0:07.9.0 core:confirm (atom-text-editor.editor.mini)
     -0:07.9.0 yo:yeoman (atom-pane.pane.active)
     -0:04.5.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript-tools, v0.6.2
atom-yeoman, v0.1.4
autocomplete-plus, v2.12.0
bezier-curve-editor, v0.6.6
color-picker, v1.7.0
css-snippets, v0.7.0
editorconfig, v1.0.0
emmet, v2.3.8
language-cshtml, v0.1.1
language-css-plus, v0.3.0
language-typescript, v0.15.0
less-than-slash, v0.6.0
linter, v0.12.1
linter-tslint, v0.2.1
minimap, v4.7.6
omnisharp-atom, v0.4.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Give 0.1.5 a try, it has simple support for the other input types, including checkboxes.
